/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type FrequencyScopeFilterOrder
 * 
 * @export
 */
export type FrequencyScopeFilterOrder = Array<string> | string;

export function FrequencyScopeFilterOrderFromJSON(json: any): FrequencyScopeFilterOrder {
    return FrequencyScopeFilterOrderFromJSONTyped(json, false);
}

export function FrequencyScopeFilterOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrequencyScopeFilterOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Array<string>FromJSONTyped(json, true), ...stringFromJSONTyped(json, true) };
}

export function FrequencyScopeFilterOrderToJSON(value?: FrequencyScopeFilterOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfArray<string>(value)) {
        return Array<string>ToJSON(value as Array<string>);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

