/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FrequencyFields } from './FrequencyFields';
import {
    FrequencyFieldsFromJSON,
    FrequencyFieldsFromJSONTyped,
    FrequencyFieldsToJSON,
} from './FrequencyFields';
import type { FrequencyIncludeFilterInner } from './FrequencyIncludeFilterInner';
import {
    FrequencyIncludeFilterInnerFromJSON,
    FrequencyIncludeFilterInnerFromJSONTyped,
    FrequencyIncludeFilterInnerToJSON,
} from './FrequencyIncludeFilterInner';
import type { FrequencyScopeFilterOrder } from './FrequencyScopeFilterOrder';
import {
    FrequencyScopeFilterOrderFromJSON,
    FrequencyScopeFilterOrderFromJSONTyped,
    FrequencyScopeFilterOrderToJSON,
} from './FrequencyScopeFilterOrder';

/**
 * 
 * @export
 * @interface FrequencyFilter
 */
export interface FrequencyFilter {
    /**
     * 
     * @type {number}
     * @memberof FrequencyFilter
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof FrequencyFilter
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof FrequencyFilter
     */
    skip?: number;
    /**
     * 
     * @type {FrequencyScopeFilterOrder}
     * @memberof FrequencyFilter
     */
    order?: FrequencyScopeFilterOrder;
    /**
     * 
     * @type {FrequencyFields}
     * @memberof FrequencyFilter
     */
    fields?: FrequencyFields;
    /**
     * 
     * @type {Array<FrequencyIncludeFilterInner>}
     * @memberof FrequencyFilter
     */
    include?: Array<FrequencyIncludeFilterInner>;
}

/**
 * Check if a given object implements the FrequencyFilter interface.
 */
export function instanceOfFrequencyFilter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FrequencyFilterFromJSON(json: any): FrequencyFilter {
    return FrequencyFilterFromJSONTyped(json, false);
}

export function FrequencyFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrequencyFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'order': !exists(json, 'order') ? undefined : FrequencyScopeFilterOrderFromJSON(json['order']),
        'fields': !exists(json, 'fields') ? undefined : FrequencyFieldsFromJSON(json['fields']),
        'include': !exists(json, 'include') ? undefined : ((json['include'] as Array<any>).map(FrequencyIncludeFilterInnerFromJSON)),
    };
}

export function FrequencyFilterToJSON(value?: FrequencyFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'skip': value.skip,
        'order': FrequencyScopeFilterOrderToJSON(value.order),
        'fields': FrequencyFieldsToJSON(value.fields),
        'include': value.include === undefined ? undefined : ((value.include as Array<any>).map(FrequencyIncludeFilterInnerToJSON)),
    };
}

