/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoopbackCount
 */
export interface LoopbackCount {
    /**
     * 
     * @type {number}
     * @memberof LoopbackCount
     */
    count?: number;
}

/**
 * Check if a given object implements the LoopbackCount interface.
 */
export function instanceOfLoopbackCount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoopbackCountFromJSON(json: any): LoopbackCount {
    return LoopbackCountFromJSONTyped(json, false);
}

export function LoopbackCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoopbackCount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function LoopbackCountToJSON(value?: LoopbackCount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
    };
}

