/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Omit<Frequency, 'id'>, schemaOptions: { title: 'NewFrequency', exclude: [ 'id' ] })
 * @export
 * @interface NewFrequency
 */
export interface NewFrequency {
    /**
     * 
     * @type {string}
     * @memberof NewFrequency
     */
    name: string;
}

/**
 * Check if a given object implements the NewFrequency interface.
 */
export function instanceOfNewFrequency(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function NewFrequencyFromJSON(json: any): NewFrequency {
    return NewFrequencyFromJSONTyped(json, false);
}

export function NewFrequencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewFrequency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NewFrequencyToJSON(value?: NewFrequency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

