/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Omit<Page, 'id'>, schemaOptions: { title: 'NewPage', exclude: [ 'id' ] })
 * @export
 * @interface NewPage
 */
export interface NewPage {
    /**
     * 
     * @type {object}
     * @memberof NewPage
     */
    doc: object;
    /**
     * 
     * @type {string}
     * @memberof NewPage
     */
    websiteId?: string;
}

/**
 * Check if a given object implements the NewPage interface.
 */
export function instanceOfNewPage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "doc" in value;

    return isInstance;
}

export function NewPageFromJSON(json: any): NewPage {
    return NewPageFromJSONTyped(json, false);
}

export function NewPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewPage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doc': json['doc'],
        'websiteId': !exists(json, 'websiteId') ? undefined : json['websiteId'],
    };
}

export function NewPageToJSON(value?: NewPage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doc': value.doc,
        'websiteId': value.websiteId,
    };
}

