/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<WebsiteError, 'id'>, 'websiteId'>, schemaOptions: { title: 'NewWebsiteErrorInWebsite', exclude: [ 'id' ], optional: [ 'websiteId' ] })
 * @export
 * @interface NewWebsiteErrorInWebsite
 */
export interface NewWebsiteErrorInWebsite {
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteErrorInWebsite
     */
    log: string;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteErrorInWebsite
     */
    websiteId?: string;
}

/**
 * Check if a given object implements the NewWebsiteErrorInWebsite interface.
 */
export function instanceOfNewWebsiteErrorInWebsite(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "log" in value;

    return isInstance;
}

export function NewWebsiteErrorInWebsiteFromJSON(json: any): NewWebsiteErrorInWebsite {
    return NewWebsiteErrorInWebsiteFromJSONTyped(json, false);
}

export function NewWebsiteErrorInWebsiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewWebsiteErrorInWebsite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'log': json['log'],
        'websiteId': !exists(json, 'websiteId') ? undefined : json['websiteId'],
    };
}

export function NewWebsiteErrorInWebsiteToJSON(value?: NewWebsiteErrorInWebsite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'log': value.log,
        'websiteId': value.websiteId,
    };
}

