/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Website, 'id'>, 'userId'>, schemaOptions: { title: 'NewWebsiteInUser', exclude: [ 'id' ], optional: [ 'userId' ] })
 * @export
 * @interface NewWebsiteInUser
 */
export interface NewWebsiteInUser {
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInUser
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof NewWebsiteInUser
     */
    pageLevels: number;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInUser
     */
    snippet: string;
    /**
     * 
     * @type {number}
     * @memberof NewWebsiteInUser
     */
    frequency?: number;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInUser
     */
    userId?: string;
}

/**
 * Check if a given object implements the NewWebsiteInUser interface.
 */
export function instanceOfNewWebsiteInUser(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "pageLevels" in value;
    isInstance = isInstance && "snippet" in value;

    return isInstance;
}

export function NewWebsiteInUserFromJSON(json: any): NewWebsiteInUser {
    return NewWebsiteInUserFromJSONTyped(json, false);
}

export function NewWebsiteInUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewWebsiteInUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'pageLevels': json['pageLevels'],
        'snippet': json['snippet'],
        'frequency': !exists(json, 'frequency') ? undefined : json['frequency'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function NewWebsiteInUserToJSON(value?: NewWebsiteInUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
        'pageLevels': value.pageLevels,
        'snippet': value.snippet,
        'frequency': value.frequency,
        'userId': value.userId,
    };
}

