/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Omit<WebsiteError, 'id'>, schemaOptions: { title: 'NewWebsiteError', exclude: [ 'id' ] })
 * @export
 * @interface NewWebsiteError
 */
export interface NewWebsiteError {
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteError
     */
    log: string;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteError
     */
    websiteId?: string;
}

/**
 * Check if a given object implements the NewWebsiteError interface.
 */
export function instanceOfNewWebsiteError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "log" in value;

    return isInstance;
}

export function NewWebsiteErrorFromJSON(json: any): NewWebsiteError {
    return NewWebsiteErrorFromJSONTyped(json, false);
}

export function NewWebsiteErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewWebsiteError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'log': json['log'],
        'websiteId': !exists(json, 'websiteId') ? undefined : json['websiteId'],
    };
}

export function NewWebsiteErrorToJSON(value?: NewWebsiteError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'log': value.log,
        'websiteId': value.websiteId,
    };
}

