/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PageFieldsOneOf } from './PageFieldsOneOf';
import {
    instanceOfPageFieldsOneOf,
    PageFieldsOneOfFromJSON,
    PageFieldsOneOfFromJSONTyped,
    PageFieldsOneOfToJSON,
} from './PageFieldsOneOf';
import type { Set<string> } from './Set&lt;string&gt;';
import {
    instanceOfSet<string>,
    Set<string>FromJSON,
    Set<string>FromJSONTyped,
    Set<string>ToJSON,
} from './Set&lt;string&gt;';

/**
 * @type PageFields
 * 
 * @export
 */
export type PageFields = PageFieldsOneOf | Set<string>;

export function PageFieldsFromJSON(json: any): PageFields {
    return PageFieldsFromJSONTyped(json, false);
}

export function PageFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...PageFieldsOneOfFromJSONTyped(json, true), ...Set<string>FromJSONTyped(json, true) };
}

export function PageFieldsToJSON(value?: PageFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfPageFieldsOneOf(value)) {
        return PageFieldsOneOfToJSON(value as PageFieldsOneOf);
    }
    if (instanceOfSet<string>(value)) {
        return Set<string>ToJSON(value as Set<string>);
    }

    return {};
}

