/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageFieldsOneOf
 */
export interface PageFieldsOneOf {
    /**
     * 
     * @type {boolean}
     * @memberof PageFieldsOneOf
     */
    doc?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageFieldsOneOf
     */
    id?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageFieldsOneOf
     */
    websiteId?: boolean;
}

/**
 * Check if a given object implements the PageFieldsOneOf interface.
 */
export function instanceOfPageFieldsOneOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageFieldsOneOfFromJSON(json: any): PageFieldsOneOf {
    return PageFieldsOneOfFromJSONTyped(json, false);
}

export function PageFieldsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageFieldsOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doc': !exists(json, 'doc') ? undefined : json['doc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'websiteId': !exists(json, 'websiteId') ? undefined : json['websiteId'],
    };
}

export function PageFieldsOneOfToJSON(value?: PageFieldsOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doc': value.doc,
        'id': value.id,
        'websiteId': value.websiteId,
    };
}

