/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageFields } from './PageFields';
import {
    PageFieldsFromJSON,
    PageFieldsFromJSONTyped,
    PageFieldsToJSON,
} from './PageFields';
import type { PageFilterOrder } from './PageFilterOrder';
import {
    PageFilterOrderFromJSON,
    PageFilterOrderFromJSONTyped,
    PageFilterOrderToJSON,
} from './PageFilterOrder';

/**
 * 
 * @export
 * @interface PageFilter1
 */
export interface PageFilter1 {
    /**
     * 
     * @type {number}
     * @memberof PageFilter1
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof PageFilter1
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof PageFilter1
     */
    skip?: number;
    /**
     * 
     * @type {PageFilterOrder}
     * @memberof PageFilter1
     */
    order?: PageFilterOrder;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PageFilter1
     */
    where?: { [key: string]: any; };
    /**
     * 
     * @type {PageFields}
     * @memberof PageFilter1
     */
    fields?: PageFields;
}

/**
 * Check if a given object implements the PageFilter1 interface.
 */
export function instanceOfPageFilter1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageFilter1FromJSON(json: any): PageFilter1 {
    return PageFilter1FromJSONTyped(json, false);
}

export function PageFilter1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PageFilter1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'order': !exists(json, 'order') ? undefined : PageFilterOrderFromJSON(json['order']),
        'where': !exists(json, 'where') ? undefined : json['where'],
        'fields': !exists(json, 'fields') ? undefined : PageFieldsFromJSON(json['fields']),
    };
}

export function PageFilter1ToJSON(value?: PageFilter1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'skip': value.skip,
        'order': PageFilterOrderToJSON(value.order),
        'where': value.where,
        'fields': PageFieldsToJSON(value.fields),
    };
}

