/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type PageFilterOrder
 * 
 * @export
 */
export type PageFilterOrder = Array<string> | string;

export function PageFilterOrderFromJSON(json: any): PageFilterOrder {
    return PageFilterOrderFromJSONTyped(json, false);
}

export function PageFilterOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageFilterOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Array<string>FromJSONTyped(json, true), ...stringFromJSONTyped(json, true) };
}

export function PageFilterOrderToJSON(value?: PageFilterOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfArray<string>(value)) {
        return Array<string>ToJSON(value as Array<string>);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

