/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PingResponseHeaders
 */
export interface PingResponseHeaders {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof PingResponseHeaders
     */
    contentType?: string;
}

/**
 * Check if a given object implements the PingResponseHeaders interface.
 */
export function instanceOfPingResponseHeaders(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PingResponseHeadersFromJSON(json: any): PingResponseHeaders {
    return PingResponseHeadersFromJSONTyped(json, false);
}

export function PingResponseHeadersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingResponseHeaders {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'contentType': !exists(json, 'Content-Type') ? undefined : json['Content-Type'],
    };
}

export function PingResponseHeadersToJSON(value?: PingResponseHeaders | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'Content-Type': value.contentType,
    };
}

