/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebsiteWithRelations } from './WebsiteWithRelations';
import {
    WebsiteWithRelationsFromJSON,
    WebsiteWithRelationsFromJSONTyped,
    WebsiteWithRelationsToJSON,
} from './WebsiteWithRelations';

/**
 * (tsType: UserWithRelations, schemaOptions: { includeRelations: true })
 * @export
 * @interface UserWithRelations
 */
export interface UserWithRelations {
    /**
     * 
     * @type {string}
     * @memberof UserWithRelations
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRelations
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserWithRelations
     */
    email: string;
    /**
     * 
     * @type {Array<WebsiteWithRelations>}
     * @memberof UserWithRelations
     */
    websites?: Array<WebsiteWithRelations>;
}

/**
 * Check if a given object implements the UserWithRelations interface.
 */
export function instanceOfUserWithRelations(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function UserWithRelationsFromJSON(json: any): UserWithRelations {
    return UserWithRelationsFromJSONTyped(json, false);
}

export function UserWithRelationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserWithRelations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'email': json['email'],
        'websites': !exists(json, 'websites') ? undefined : ((json['websites'] as Array<any>).map(WebsiteWithRelationsFromJSON)),
    };
}

export function UserWithRelationsToJSON(value?: UserWithRelations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'websites': value.websites === undefined ? undefined : ((value.websites as Array<any>).map(WebsiteWithRelationsToJSON)),
    };
}

