/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageFilterOrder } from './PageFilterOrder';
import {
    PageFilterOrderFromJSON,
    PageFilterOrderFromJSONTyped,
    PageFilterOrderToJSON,
} from './PageFilterOrder';
import type { UserFields } from './UserFields';
import {
    UserFieldsFromJSON,
    UserFieldsFromJSONTyped,
    UserFieldsToJSON,
} from './UserFields';
import type { UserIncludeFilterInner } from './UserIncludeFilterInner';
import {
    UserIncludeFilterInnerFromJSON,
    UserIncludeFilterInnerFromJSONTyped,
    UserIncludeFilterInnerToJSON,
} from './UserIncludeFilterInner';

/**
 * 
 * @export
 * @interface UserFilter1
 */
export interface UserFilter1 {
    /**
     * 
     * @type {number}
     * @memberof UserFilter1
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof UserFilter1
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserFilter1
     */
    skip?: number;
    /**
     * 
     * @type {PageFilterOrder}
     * @memberof UserFilter1
     */
    order?: PageFilterOrder;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UserFilter1
     */
    where?: { [key: string]: any; };
    /**
     * 
     * @type {UserFields}
     * @memberof UserFilter1
     */
    fields?: UserFields;
    /**
     * 
     * @type {Array<UserIncludeFilterInner>}
     * @memberof UserFilter1
     */
    include?: Array<UserIncludeFilterInner>;
}

/**
 * Check if a given object implements the UserFilter1 interface.
 */
export function instanceOfUserFilter1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserFilter1FromJSON(json: any): UserFilter1 {
    return UserFilter1FromJSONTyped(json, false);
}

export function UserFilter1FromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFilter1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'order': !exists(json, 'order') ? undefined : PageFilterOrderFromJSON(json['order']),
        'where': !exists(json, 'where') ? undefined : json['where'],
        'fields': !exists(json, 'fields') ? undefined : UserFieldsFromJSON(json['fields']),
        'include': !exists(json, 'include') ? undefined : ((json['include'] as Array<any>).map(UserIncludeFilterInnerFromJSON)),
    };
}

export function UserFilter1ToJSON(value?: UserFilter1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'skip': value.skip,
        'order': PageFilterOrderToJSON(value.order),
        'where': value.where,
        'fields': UserFieldsToJSON(value.fields),
        'include': value.include === undefined ? undefined : ((value.include as Array<any>).map(UserIncludeFilterInnerToJSON)),
    };
}

