/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Set<string> } from './Set&lt;string&gt;';
import {
    instanceOfSet<string>,
    Set<string>FromJSON,
    Set<string>FromJSONTyped,
    Set<string>ToJSON,
} from './Set&lt;string&gt;';
import type { UserFieldsOneOf } from './UserFieldsOneOf';
import {
    instanceOfUserFieldsOneOf,
    UserFieldsOneOfFromJSON,
    UserFieldsOneOfFromJSONTyped,
    UserFieldsOneOfToJSON,
} from './UserFieldsOneOf';

/**
 * @type UserFields
 * 
 * @export
 */
export type UserFields = Set<string> | UserFieldsOneOf;

export function UserFieldsFromJSON(json: any): UserFields {
    return UserFieldsFromJSONTyped(json, false);
}

export function UserFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Set<string>FromJSONTyped(json, true), ...UserFieldsOneOfFromJSONTyped(json, true) };
}

export function UserFieldsToJSON(value?: UserFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfSet<string>(value)) {
        return Set<string>ToJSON(value as Set<string>);
    }
    if (instanceOfUserFieldsOneOf(value)) {
        return UserFieldsOneOfToJSON(value as UserFieldsOneOf);
    }

    return {};
}

