/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Partial<WebsiteError>, schemaOptions: { partial: true })
 * @export
 * @interface WebsiteErrorPartial
 */
export interface WebsiteErrorPartial {
    /**
     * 
     * @type {string}
     * @memberof WebsiteErrorPartial
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WebsiteErrorPartial
     */
    log?: string;
    /**
     * 
     * @type {string}
     * @memberof WebsiteErrorPartial
     */
    websiteId?: string;
}

/**
 * Check if a given object implements the WebsiteErrorPartial interface.
 */
export function instanceOfWebsiteErrorPartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebsiteErrorPartialFromJSON(json: any): WebsiteErrorPartial {
    return WebsiteErrorPartialFromJSONTyped(json, false);
}

export function WebsiteErrorPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteErrorPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'log': !exists(json, 'log') ? undefined : json['log'],
        'websiteId': !exists(json, 'websiteId') ? undefined : json['websiteId'],
    };
}

export function WebsiteErrorPartialToJSON(value?: WebsiteErrorPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'log': value.log,
        'websiteId': value.websiteId,
    };
}

