/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Partial<Website>, schemaOptions: { partial: true })
 * @export
 * @interface WebsitePartial
 */
export interface WebsitePartial {
    /**
     * 
     * @type {string}
     * @memberof WebsitePartial
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WebsitePartial
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof WebsitePartial
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof WebsitePartial
     */
    pageLevels?: number;
    /**
     * 
     * @type {string}
     * @memberof WebsitePartial
     */
    snippet?: string;
    /**
     * 
     * @type {number}
     * @memberof WebsitePartial
     */
    frequency?: number;
    /**
     * 
     * @type {string}
     * @memberof WebsitePartial
     */
    userId?: string;
}

/**
 * Check if a given object implements the WebsitePartial interface.
 */
export function instanceOfWebsitePartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebsitePartialFromJSON(json: any): WebsitePartial {
    return WebsitePartialFromJSONTyped(json, false);
}

export function WebsitePartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsitePartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'pageLevels': !exists(json, 'pageLevels') ? undefined : json['pageLevels'],
        'snippet': !exists(json, 'snippet') ? undefined : json['snippet'],
        'frequency': !exists(json, 'frequency') ? undefined : json['frequency'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function WebsitePartialToJSON(value?: WebsitePartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'url': value.url,
        'pageLevels': value.pageLevels,
        'snippet': value.snippet,
        'frequency': value.frequency,
        'userId': value.userId,
    };
}

