/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LoopbackCount,
  NewWebsiteInFrequency,
  Website,
  WebsitePartial,
} from '../models/index';
import {
    LoopbackCountFromJSON,
    LoopbackCountToJSON,
    NewWebsiteInFrequencyFromJSON,
    NewWebsiteInFrequencyToJSON,
    WebsiteFromJSON,
    WebsiteToJSON,
    WebsitePartialFromJSON,
    WebsitePartialToJSON,
} from '../models/index';

export interface FrequencyWebsiteControllerCreateRequest {
    id: string;
    newWebsiteInFrequency?: NewWebsiteInFrequency;
}

export interface FrequencyWebsiteControllerDeleteRequest {
    id: string;
    where?: { [key: string]: any; };
}

export interface FrequencyWebsiteControllerFindRequest {
    id: string;
    filter?: { [key: string]: any; };
}

export interface FrequencyWebsiteControllerPatchRequest {
    id: string;
    where?: { [key: string]: any; };
    websitePartial?: WebsitePartial;
}

/**
 * 
 */
export class FrequencyWebsiteControllerApi extends runtime.BaseAPI {

    /**
     */
    async frequencyWebsiteControllerCreateRaw(requestParameters: FrequencyWebsiteControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Website>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling frequencyWebsiteControllerCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/frequencies/{id}/websites`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NewWebsiteInFrequencyToJSON(requestParameters.newWebsiteInFrequency),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebsiteFromJSON(jsonValue));
    }

    /**
     */
    async frequencyWebsiteControllerCreate(requestParameters: FrequencyWebsiteControllerCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Website> {
        const response = await this.frequencyWebsiteControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async frequencyWebsiteControllerDeleteRaw(requestParameters: FrequencyWebsiteControllerDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoopbackCount>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling frequencyWebsiteControllerDelete.');
        }

        const queryParameters: any = {};

        if (requestParameters.where !== undefined) {
            queryParameters['where'] = requestParameters.where;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/frequencies/{id}/websites`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoopbackCountFromJSON(jsonValue));
    }

    /**
     */
    async frequencyWebsiteControllerDelete(requestParameters: FrequencyWebsiteControllerDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoopbackCount> {
        const response = await this.frequencyWebsiteControllerDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async frequencyWebsiteControllerFindRaw(requestParameters: FrequencyWebsiteControllerFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Website>>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling frequencyWebsiteControllerFind.');
        }

        const queryParameters: any = {};

        if (requestParameters.filter !== undefined) {
            queryParameters['filter'] = requestParameters.filter;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/frequencies/{id}/websites`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebsiteFromJSON));
    }

    /**
     */
    async frequencyWebsiteControllerFind(requestParameters: FrequencyWebsiteControllerFindRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Website>> {
        const response = await this.frequencyWebsiteControllerFindRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async frequencyWebsiteControllerPatchRaw(requestParameters: FrequencyWebsiteControllerPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoopbackCount>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling frequencyWebsiteControllerPatch.');
        }

        const queryParameters: any = {};

        if (requestParameters.where !== undefined) {
            queryParameters['where'] = requestParameters.where;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/frequencies/{id}/websites`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WebsitePartialToJSON(requestParameters.websitePartial),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoopbackCountFromJSON(jsonValue));
    }

    /**
     */
    async frequencyWebsiteControllerPatch(requestParameters: FrequencyWebsiteControllerPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoopbackCount> {
        const response = await this.frequencyWebsiteControllerPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
