/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FrequencyFieldsOneOf
 */
export interface FrequencyFieldsOneOf {
    /**
     * 
     * @type {boolean}
     * @memberof FrequencyFieldsOneOf
     */
    name?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FrequencyFieldsOneOf
     */
    id?: boolean;
}

/**
 * Check if a given object implements the FrequencyFieldsOneOf interface.
 */
export function instanceOfFrequencyFieldsOneOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FrequencyFieldsOneOfFromJSON(json: any): FrequencyFieldsOneOf {
    return FrequencyFieldsOneOfFromJSONTyped(json, false);
}

export function FrequencyFieldsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrequencyFieldsOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function FrequencyFieldsOneOfToJSON(value?: FrequencyFieldsOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
    };
}

