/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type FrequencyScopeFilterFields
 * 
 * @export
 */
export type FrequencyScopeFilterFields = Set<string> | { [key: string]: any; };

export function FrequencyScopeFilterFieldsFromJSON(json: any): FrequencyScopeFilterFields {
    return FrequencyScopeFilterFieldsFromJSONTyped(json, false);
}

export function FrequencyScopeFilterFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FrequencyScopeFilterFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Set<string>FromJSONTyped(json, true), ...{ [key: string]: any; }FromJSONTyped(json, true) };
}

export function FrequencyScopeFilterFieldsToJSON(value?: FrequencyScopeFilterFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfSet<string>(value)) {
        return Set<string>ToJSON(value as Set<string>);
    }
    if (instanceOf{ [key: string]: any; }(value)) {
        return { [key: string]: any; }ToJSON(value as { [key: string]: any; });
    }

    return {};
}

