/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: @loopback/repository-json-schema#Optional<Omit<Website, 'id'>, 'frequencyId'>, schemaOptions: { title: 'NewWebsiteInFrequency', exclude: [ 'id' ], optional: [ 'frequencyId' ] })
 * @export
 * @interface NewWebsiteInFrequency
 */
export interface NewWebsiteInFrequency {
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInFrequency
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInFrequency
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof NewWebsiteInFrequency
     */
    pageLevels: number;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInFrequency
     */
    snippet: string;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInFrequency
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof NewWebsiteInFrequency
     */
    frequencyId?: string;
}

/**
 * Check if a given object implements the NewWebsiteInFrequency interface.
 */
export function instanceOfNewWebsiteInFrequency(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "pageLevels" in value;
    isInstance = isInstance && "snippet" in value;

    return isInstance;
}

export function NewWebsiteInFrequencyFromJSON(json: any): NewWebsiteInFrequency {
    return NewWebsiteInFrequencyFromJSONTyped(json, false);
}

export function NewWebsiteInFrequencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewWebsiteInFrequency {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'pageLevels': json['pageLevels'],
        'snippet': json['snippet'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'frequencyId': !exists(json, 'frequencyId') ? undefined : json['frequencyId'],
    };
}

export function NewWebsiteInFrequencyToJSON(value?: NewWebsiteInFrequency | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'url': value.url,
        'pageLevels': value.pageLevels,
        'snippet': value.snippet,
        'userId': value.userId,
        'frequencyId': value.frequencyId,
    };
}

