/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageFields } from './PageFields';
import {
    PageFieldsFromJSON,
    PageFieldsFromJSONTyped,
    PageFieldsToJSON,
} from './PageFields';
import type { PageFilterOrder } from './PageFilterOrder';
import {
    PageFilterOrderFromJSON,
    PageFilterOrderFromJSONTyped,
    PageFilterOrderToJSON,
} from './PageFilterOrder';

/**
 * 
 * @export
 * @interface PageFilter
 */
export interface PageFilter {
    /**
     * 
     * @type {number}
     * @memberof PageFilter
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof PageFilter
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof PageFilter
     */
    skip?: number;
    /**
     * 
     * @type {PageFilterOrder}
     * @memberof PageFilter
     */
    order?: PageFilterOrder;
    /**
     * 
     * @type {PageFields}
     * @memberof PageFilter
     */
    fields?: PageFields;
}

/**
 * Check if a given object implements the PageFilter interface.
 */
export function instanceOfPageFilter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PageFilterFromJSON(json: any): PageFilter {
    return PageFilterFromJSONTyped(json, false);
}

export function PageFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'order': !exists(json, 'order') ? undefined : PageFilterOrderFromJSON(json['order']),
        'fields': !exists(json, 'fields') ? undefined : PageFieldsFromJSON(json['fields']),
    };
}

export function PageFilterToJSON(value?: PageFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'skip': value.skip,
        'order': PageFilterOrderToJSON(value.order),
        'fields': PageFieldsToJSON(value.fields),
    };
}

