/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: PageWithRelations, schemaOptions: { includeRelations: true })
 * @export
 * @interface PageWithRelations
 */
export interface PageWithRelations {
    /**
     * 
     * @type {object}
     * @memberof PageWithRelations
     */
    doc: object;
    /**
     * 
     * @type {string}
     * @memberof PageWithRelations
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PageWithRelations
     */
    websiteId?: string;
}

/**
 * Check if a given object implements the PageWithRelations interface.
 */
export function instanceOfPageWithRelations(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "doc" in value;

    return isInstance;
}

export function PageWithRelationsFromJSON(json: any): PageWithRelations {
    return PageWithRelationsFromJSONTyped(json, false);
}

export function PageWithRelationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageWithRelations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doc': json['doc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'websiteId': !exists(json, 'websiteId') ? undefined : json['websiteId'],
    };
}

export function PageWithRelationsToJSON(value?: PageWithRelations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doc': value.doc,
        'id': value.id,
        'websiteId': value.websiteId,
    };
}

