/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Partial<Page>, schemaOptions: { partial: true })
 * @export
 * @interface PagePartial
 */
export interface PagePartial {
    /**
     * 
     * @type {object}
     * @memberof PagePartial
     */
    doc?: object;
    /**
     * 
     * @type {string}
     * @memberof PagePartial
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PagePartial
     */
    websiteId?: string;
}

/**
 * Check if a given object implements the PagePartial interface.
 */
export function instanceOfPagePartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagePartialFromJSON(json: any): PagePartial {
    return PagePartialFromJSONTyped(json, false);
}

export function PagePartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagePartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'doc': !exists(json, 'doc') ? undefined : json['doc'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'websiteId': !exists(json, 'websiteId') ? undefined : json['websiteId'],
    };
}

export function PagePartialToJSON(value?: PagePartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'doc': value.doc,
        'id': value.id,
        'websiteId': value.websiteId,
    };
}

