/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PingResponseHeaders } from './PingResponseHeaders';
import {
    PingResponseHeadersFromJSON,
    PingResponseHeadersFromJSONTyped,
    PingResponseHeadersToJSON,
} from './PingResponseHeaders';

/**
 * 
 * @export
 * @interface PingResponse
 */
export interface PingResponse {
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    greeting?: string;
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof PingResponse
     */
    url?: string;
    /**
     * 
     * @type {PingResponseHeaders}
     * @memberof PingResponse
     */
    headers?: PingResponseHeaders;
}

/**
 * Check if a given object implements the PingResponse interface.
 */
export function instanceOfPingResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PingResponseFromJSON(json: any): PingResponse {
    return PingResponseFromJSONTyped(json, false);
}

export function PingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'greeting': !exists(json, 'greeting') ? undefined : json['greeting'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'headers': !exists(json, 'headers') ? undefined : PingResponseHeadersFromJSON(json['headers']),
    };
}

export function PingResponseToJSON(value?: PingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'greeting': value.greeting,
        'date': value.date,
        'url': value.url,
        'headers': PingResponseHeadersToJSON(value.headers),
    };
}

