/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserIncludeFilterItems } from './UserIncludeFilterItems';
import {
    UserIncludeFilterItemsFromJSON,
    UserIncludeFilterItemsFromJSONTyped,
    UserIncludeFilterItemsToJSON,
} from './UserIncludeFilterItems';
import type { UserScopeFilter } from './UserScopeFilter';
import {
    UserScopeFilterFromJSON,
    UserScopeFilterFromJSONTyped,
    UserScopeFilterToJSON,
} from './UserScopeFilter';

/**
 * 
 * @export
 * @interface UserIncludeFilterInner
 */
export interface UserIncludeFilterInner {
    /**
     * 
     * @type {string}
     * @memberof UserIncludeFilterInner
     */
    relation?: UserIncludeFilterInnerRelationEnum;
    /**
     * 
     * @type {UserScopeFilter}
     * @memberof UserIncludeFilterInner
     */
    scope?: UserScopeFilter;
}


/**
 * @export
 */
export const UserIncludeFilterInnerRelationEnum = {
    Websites: 'websites'
} as const;
export type UserIncludeFilterInnerRelationEnum = typeof UserIncludeFilterInnerRelationEnum[keyof typeof UserIncludeFilterInnerRelationEnum];


/**
 * Check if a given object implements the UserIncludeFilterInner interface.
 */
export function instanceOfUserIncludeFilterInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserIncludeFilterInnerFromJSON(json: any): UserIncludeFilterInner {
    return UserIncludeFilterInnerFromJSONTyped(json, false);
}

export function UserIncludeFilterInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIncludeFilterInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'relation': !exists(json, 'relation') ? undefined : json['relation'],
        'scope': !exists(json, 'scope') ? undefined : UserScopeFilterFromJSON(json['scope']),
    };
}

export function UserIncludeFilterInnerToJSON(value?: UserIncludeFilterInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'relation': value.relation,
        'scope': UserScopeFilterToJSON(value.scope),
    };
}

