/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserFieldsOneOf
 */
export interface UserFieldsOneOf {
    /**
     * 
     * @type {boolean}
     * @memberof UserFieldsOneOf
     */
    id?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserFieldsOneOf
     */
    name?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserFieldsOneOf
     */
    email?: boolean;
}

/**
 * Check if a given object implements the UserFieldsOneOf interface.
 */
export function instanceOfUserFieldsOneOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserFieldsOneOfFromJSON(json: any): UserFieldsOneOf {
    return UserFieldsOneOfFromJSONTyped(json, false);
}

export function UserFieldsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFieldsOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UserFieldsOneOfToJSON(value?: UserFieldsOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
    };
}

