/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Partial<User>, schemaOptions: { partial: true })
 * @export
 * @interface UserPartial
 */
export interface UserPartial {
    /**
     * 
     * @type {string}
     * @memberof UserPartial
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPartial
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPartial
     */
    email?: string;
}

/**
 * Check if a given object implements the UserPartial interface.
 */
export function instanceOfUserPartial(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserPartialFromJSON(json: any): UserPartial {
    return UserPartialFromJSONTyped(json, false);
}

export function UserPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UserPartialToJSON(value?: UserPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
    };
}

