/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageFilterOrder } from './PageFilterOrder';
import {
    PageFilterOrderFromJSON,
    PageFilterOrderFromJSONTyped,
    PageFilterOrderToJSON,
} from './PageFilterOrder';
import type { UserScopeFilterFields } from './UserScopeFilterFields';
import {
    UserScopeFilterFieldsFromJSON,
    UserScopeFilterFieldsFromJSONTyped,
    UserScopeFilterFieldsToJSON,
} from './UserScopeFilterFields';

/**
 * 
 * @export
 * @interface UserScopeFilter
 */
export interface UserScopeFilter {
    /**
     * 
     * @type {number}
     * @memberof UserScopeFilter
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof UserScopeFilter
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof UserScopeFilter
     */
    skip?: number;
    /**
     * 
     * @type {PageFilterOrder}
     * @memberof UserScopeFilter
     */
    order?: PageFilterOrder;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UserScopeFilter
     */
    where?: { [key: string]: any; };
    /**
     * 
     * @type {UserScopeFilterFields}
     * @memberof UserScopeFilter
     */
    fields?: UserScopeFilterFields;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof UserScopeFilter
     */
    include?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the UserScopeFilter interface.
 */
export function instanceOfUserScopeFilter(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserScopeFilterFromJSON(json: any): UserScopeFilter {
    return UserScopeFilterFromJSONTyped(json, false);
}

export function UserScopeFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserScopeFilter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'order': !exists(json, 'order') ? undefined : PageFilterOrderFromJSON(json['order']),
        'where': !exists(json, 'where') ? undefined : json['where'],
        'fields': !exists(json, 'fields') ? undefined : UserScopeFilterFieldsFromJSON(json['fields']),
        'include': !exists(json, 'include') ? undefined : json['include'],
    };
}

export function UserScopeFilterToJSON(value?: UserScopeFilter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'skip': value.skip,
        'order': PageFilterOrderToJSON(value.order),
        'where': value.where,
        'fields': UserScopeFilterFieldsToJSON(value.fields),
        'include': value.include,
    };
}

