/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FrequencyScopeFilterOrder } from './FrequencyScopeFilterOrder';
import {
    FrequencyScopeFilterOrderFromJSON,
    FrequencyScopeFilterOrderFromJSONTyped,
    FrequencyScopeFilterOrderToJSON,
} from './FrequencyScopeFilterOrder';
import type { WebsiteFields } from './WebsiteFields';
import {
    WebsiteFieldsFromJSON,
    WebsiteFieldsFromJSONTyped,
    WebsiteFieldsToJSON,
} from './WebsiteFields';

/**
 * 
 * @export
 * @interface WebsiteFilter1
 */
export interface WebsiteFilter1 {
    /**
     * 
     * @type {number}
     * @memberof WebsiteFilter1
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof WebsiteFilter1
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof WebsiteFilter1
     */
    skip?: number;
    /**
     * 
     * @type {FrequencyScopeFilterOrder}
     * @memberof WebsiteFilter1
     */
    order?: FrequencyScopeFilterOrder;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WebsiteFilter1
     */
    where?: { [key: string]: any; };
    /**
     * 
     * @type {WebsiteFields}
     * @memberof WebsiteFilter1
     */
    fields?: WebsiteFields;
}

/**
 * Check if a given object implements the WebsiteFilter1 interface.
 */
export function instanceOfWebsiteFilter1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebsiteFilter1FromJSON(json: any): WebsiteFilter1 {
    return WebsiteFilter1FromJSONTyped(json, false);
}

export function WebsiteFilter1FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteFilter1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'order': !exists(json, 'order') ? undefined : FrequencyScopeFilterOrderFromJSON(json['order']),
        'where': !exists(json, 'where') ? undefined : json['where'],
        'fields': !exists(json, 'fields') ? undefined : WebsiteFieldsFromJSON(json['fields']),
    };
}

export function WebsiteFilter1ToJSON(value?: WebsiteFilter1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'skip': value.skip,
        'order': FrequencyScopeFilterOrderToJSON(value.order),
        'where': value.where,
        'fields': WebsiteFieldsToJSON(value.fields),
    };
}

