/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebsiteError
 */
export interface WebsiteError {
    /**
     * 
     * @type {string}
     * @memberof WebsiteError
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WebsiteError
     */
    log: string;
    /**
     * 
     * @type {string}
     * @memberof WebsiteError
     */
    websiteId?: string;
}

/**
 * Check if a given object implements the WebsiteError interface.
 */
export function instanceOfWebsiteError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "log" in value;

    return isInstance;
}

export function WebsiteErrorFromJSON(json: any): WebsiteError {
    return WebsiteErrorFromJSONTyped(json, false);
}

export function WebsiteErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'log': json['log'],
        'websiteId': !exists(json, 'websiteId') ? undefined : json['websiteId'],
    };
}

export function WebsiteErrorToJSON(value?: WebsiteError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'log': value.log,
        'websiteId': value.websiteId,
    };
}

