/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PageFilterOrder } from './PageFilterOrder';
import {
    PageFilterOrderFromJSON,
    PageFilterOrderFromJSONTyped,
    PageFilterOrderToJSON,
} from './PageFilterOrder';
import type { WebsiteFields } from './WebsiteFields';
import {
    WebsiteFieldsFromJSON,
    WebsiteFieldsFromJSONTyped,
    WebsiteFieldsToJSON,
} from './WebsiteFields';
import type { WebsiteIncludeFilterInner } from './WebsiteIncludeFilterInner';
import {
    WebsiteIncludeFilterInnerFromJSON,
    WebsiteIncludeFilterInnerFromJSONTyped,
    WebsiteIncludeFilterInnerToJSON,
} from './WebsiteIncludeFilterInner';

/**
 * 
 * @export
 * @interface WebsiteFilter1
 */
export interface WebsiteFilter1 {
    /**
     * 
     * @type {number}
     * @memberof WebsiteFilter1
     */
    offset?: number;
    /**
     * 
     * @type {number}
     * @memberof WebsiteFilter1
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof WebsiteFilter1
     */
    skip?: number;
    /**
     * 
     * @type {PageFilterOrder}
     * @memberof WebsiteFilter1
     */
    order?: PageFilterOrder;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WebsiteFilter1
     */
    where?: { [key: string]: any; };
    /**
     * 
     * @type {WebsiteFields}
     * @memberof WebsiteFilter1
     */
    fields?: WebsiteFields;
    /**
     * 
     * @type {Array<WebsiteIncludeFilterInner>}
     * @memberof WebsiteFilter1
     */
    include?: Array<WebsiteIncludeFilterInner>;
}

/**
 * Check if a given object implements the WebsiteFilter1 interface.
 */
export function instanceOfWebsiteFilter1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebsiteFilter1FromJSON(json: any): WebsiteFilter1 {
    return WebsiteFilter1FromJSONTyped(json, false);
}

export function WebsiteFilter1FromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteFilter1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'offset': !exists(json, 'offset') ? undefined : json['offset'],
        'limit': !exists(json, 'limit') ? undefined : json['limit'],
        'skip': !exists(json, 'skip') ? undefined : json['skip'],
        'order': !exists(json, 'order') ? undefined : PageFilterOrderFromJSON(json['order']),
        'where': !exists(json, 'where') ? undefined : json['where'],
        'fields': !exists(json, 'fields') ? undefined : WebsiteFieldsFromJSON(json['fields']),
        'include': !exists(json, 'include') ? undefined : ((json['include'] as Array<any>).map(WebsiteIncludeFilterInnerFromJSON)),
    };
}

export function WebsiteFilter1ToJSON(value?: WebsiteFilter1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'offset': value.offset,
        'limit': value.limit,
        'skip': value.skip,
        'order': PageFilterOrderToJSON(value.order),
        'where': value.where,
        'fields': WebsiteFieldsToJSON(value.fields),
        'include': value.include === undefined ? undefined : ((value.include as Array<any>).map(WebsiteIncludeFilterInnerToJSON)),
    };
}

