/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebsiteFieldsOneOf
 */
export interface WebsiteFieldsOneOf {
    /**
     * 
     * @type {boolean}
     * @memberof WebsiteFieldsOneOf
     */
    id?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WebsiteFieldsOneOf
     */
    name?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WebsiteFieldsOneOf
     */
    url?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WebsiteFieldsOneOf
     */
    pageLevels?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WebsiteFieldsOneOf
     */
    snippet?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WebsiteFieldsOneOf
     */
    userId?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WebsiteFieldsOneOf
     */
    frequencyId?: boolean;
}

/**
 * Check if a given object implements the WebsiteFieldsOneOf interface.
 */
export function instanceOfWebsiteFieldsOneOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebsiteFieldsOneOfFromJSON(json: any): WebsiteFieldsOneOf {
    return WebsiteFieldsOneOfFromJSONTyped(json, false);
}

export function WebsiteFieldsOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteFieldsOneOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'pageLevels': !exists(json, 'pageLevels') ? undefined : json['pageLevels'],
        'snippet': !exists(json, 'snippet') ? undefined : json['snippet'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'frequencyId': !exists(json, 'frequencyId') ? undefined : json['frequencyId'],
    };
}

export function WebsiteFieldsOneOfToJSON(value?: WebsiteFieldsOneOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'url': value.url,
        'pageLevels': value.pageLevels,
        'snippet': value.snippet,
        'userId': value.userId,
        'frequencyId': value.frequencyId,
    };
}

