/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Website
 */
export interface Website {
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof Website
     */
    pageLevels: number;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    snippet: string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Website
     */
    frequencyId?: string;
}

/**
 * Check if a given object implements the Website interface.
 */
export function instanceOfWebsite(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "pageLevels" in value;
    isInstance = isInstance && "snippet" in value;

    return isInstance;
}

export function WebsiteFromJSON(json: any): Website {
    return WebsiteFromJSONTyped(json, false);
}

export function WebsiteFromJSONTyped(json: any, ignoreDiscriminator: boolean): Website {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'url': json['url'],
        'pageLevels': json['pageLevels'],
        'snippet': json['snippet'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'frequencyId': !exists(json, 'frequencyId') ? undefined : json['frequencyId'],
    };
}

export function WebsiteToJSON(value?: Website | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'url': value.url,
        'pageLevels': value.pageLevels,
        'snippet': value.snippet,
        'userId': value.userId,
        'frequencyId': value.frequencyId,
    };
}

