/* tslint:disable */
/* eslint-disable */
/**
 * package or prject name
 * Website crawling
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Set<string> } from './Set&lt;string&gt;';
import {
    instanceOfSet<string>,
    Set<string>FromJSON,
    Set<string>FromJSONTyped,
    Set<string>ToJSON,
} from './Set&lt;string&gt;';
import type { WebsiteErrorFieldsOneOf } from './WebsiteErrorFieldsOneOf';
import {
    instanceOfWebsiteErrorFieldsOneOf,
    WebsiteErrorFieldsOneOfFromJSON,
    WebsiteErrorFieldsOneOfFromJSONTyped,
    WebsiteErrorFieldsOneOfToJSON,
} from './WebsiteErrorFieldsOneOf';

/**
 * @type WebsiteErrorFields
 * 
 * @export
 */
export type WebsiteErrorFields = Set<string> | WebsiteErrorFieldsOneOf;

export function WebsiteErrorFieldsFromJSON(json: any): WebsiteErrorFields {
    return WebsiteErrorFieldsFromJSONTyped(json, false);
}

export function WebsiteErrorFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteErrorFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Set<string>FromJSONTyped(json, true), ...WebsiteErrorFieldsOneOfFromJSONTyped(json, true) };
}

export function WebsiteErrorFieldsToJSON(value?: WebsiteErrorFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfSet<string>(value)) {
        return Set<string>ToJSON(value as Set<string>);
    }
    if (instanceOfWebsiteErrorFieldsOneOf(value)) {
        return WebsiteErrorFieldsOneOfToJSON(value as WebsiteErrorFieldsOneOf);
    }

    return {};
}

