/* tslint:disable */
/* eslint-disable */
/**
 * searchservice
 * Website crawling
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Set<string> } from './Set&lt;string&gt;';
import {
    instanceOfSet<string>,
    Set<string>FromJSON,
    Set<string>FromJSONTyped,
    Set<string>ToJSON,
} from './Set&lt;string&gt;';
import type { WebsiteFieldsOneOf } from './WebsiteFieldsOneOf';
import {
    instanceOfWebsiteFieldsOneOf,
    WebsiteFieldsOneOfFromJSON,
    WebsiteFieldsOneOfFromJSONTyped,
    WebsiteFieldsOneOfToJSON,
} from './WebsiteFieldsOneOf';

/**
 * @type WebsiteFields
 * 
 * @export
 */
export type WebsiteFields = Set<string> | WebsiteFieldsOneOf;

export function WebsiteFieldsFromJSON(json: any): WebsiteFields {
    return WebsiteFieldsFromJSONTyped(json, false);
}

export function WebsiteFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebsiteFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...Set<string>FromJSONTyped(json, true), ...WebsiteFieldsOneOfFromJSONTyped(json, true) };
}

export function WebsiteFieldsToJSON(value?: WebsiteFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfSet<string>(value)) {
        return Set<string>ToJSON(value as Set<string>);
    }
    if (instanceOfWebsiteFieldsOneOf(value)) {
        return WebsiteFieldsOneOfToJSON(value as WebsiteFieldsOneOf);
    }

    return {};
}

